package io.github.TyPit.listenerTemplate.items;

public enum ItemId {
    SILVER_CHAIN_LINK,
    SHOOTING_GLASSES,
    CARBON_COPY,
    TENNISON_GAMBIT,
    BLAST_SCRIPT,
    EMERGENCY_PULSE,
    MONOTYPE_RIBBON,
    SLIPSTREAM,
    MARGIN_NOTES,
    DEAD_LETTER_OFFICE,
    STATIC_MARGIN,
    PANIC_SHIELD,
    OVERFLOW_SCRIPT,
    FINAL_DRAFT,
    SHARPENED_ROUNDS,
    CORE_PLATING,
    BOUNTY_LEDGER,
    ROUND_DIVIDEND,
    MAFIA_CONTRACT
}
